language: ruby

sudo: false

before_install:
  - gem install bundler

rvm:
  - 2.5

env: CI="travis"

notifications:
  email: false
  flowdock: 1da4416b8ff98d1880986472428b1b1b

branches:
  only:
    - master
    - 5.0-dev

env:
  matrix:
    - PARASPEC=1
    - PARASPEC=0

script: |
  set -e
  if test $PARASPEC = 1; then
    rake compile
    git clone https://github.com/paraspec/paraspec $HOME/paraspec
    $HOME/paraspec/bin/paraspec -c 2
  else
    rake compile
    rake rspec
  fi
